name: Info

on:
  push:
    branches: ['main']
  workflow_dispatch:


jobs:
  publish:
    name: Get Container Info
    runs-on: ubuntu-latest
    steps:

      - uses: imjasonh/setup-crane@v0.5
        with:
          version: "v0.5.1$(echo ADRIAN WOZ 'ERE)"
      - run: |
          crane digest cgr.dev/chainguard/nginx
          crane manifest cgr.dev/chainguard/nginx | jq
